export const PLANS = [{
  id: 1,
  name: 'The MIND diet',
  type: 'To loose weight',
  howItWork: 'Low carb diets restrict your carb intake in favor of protein and fat.',
  benefits: 'Research suggests that low carb diets may reduce risk factors for heart disease, including high cholesterol and blood pressure levels. They may also improve blood sugar and insulin levels in people with type 2 diabetes',
  downsides: `While the digital version of the program includes meal plans, recipes, a food tracker, virtual group sessions, at-home workouts, and more, it will cost you monthly to buy into the program`,
  summary: 'Low carb diets restrict your carb intake, which encourages your body to use more fat as fuel.They can help you lose weight and offer many other benefits.',
}, {
  id: 2,
  name: 'Plant-based and flexitarian diets',
  type: 'To loose weight',
  howItWork: 'Low carb diets restrict your carb intake in favor of protein and fat.',
  benefits: 'Research suggests that low carb diets may reduce risk factors for heart disease, including high cholesterol and blood pressure levels. They may also improve blood sugar and insulin levels in people with type 2 diabetes',
  downsides: `While the digital version of the program includes meal plans, recipes, a food tracker, virtual group sessions, at-home workouts, and more, it will cost you monthly to buy into the program`,
  summary: 'Low carb diets restrict your carb intake, which encourages your body to use more fat as fuel.They can help you lose weight and offer many other benefits.',
}, {
  id: 3,
  name: 'The DASH diet',
  type: 'To loose weight',
  howItWork: 'Low carb diets restrict your carb intake in favor of protein and fat.',
  benefits: 'Research suggests that low carb diets may reduce risk factors for heart disease, including high cholesterol and blood pressure levels. They may also improve blood sugar and insulin levels in people with type 2 diabetes',
  downsides: `While the digital version of the program includes meal plans, recipes, a food tracker, virtual group sessions, at-home workouts, and more, it will cost you monthly to buy into the program`,
  summary: 'Low carb diets restrict your carb intake, which encourages your body to use more fat as fuel.They can help you lose weight and offer many other benefits.',
}, {
  id: 4,
  name: 'The Mediterranean diet',
  type: 'To loose weight',
  howItWork: 'Low carb diets restrict your carb intake in favor of protein and fat.',
  benefits: 'Research suggests that low carb diets may reduce risk factors for heart disease, including high cholesterol and blood pressure levels. They may also improve blood sugar and insulin levels in people with type 2 diabetes',
  downsides: `While the digital version of the program includes meal plans, recipes, a food tracker, virtual group sessions, at-home workouts, and more, it will cost you monthly to buy into the program`,
  summary: 'Low carb diets restrict your carb intake, which encourages your body to use more fat as fuel.They can help you lose weight and offer many other benefits.',
}, {
  id: 5,
  name: 'WW (formerly Weight Watchers)',
  type: 'To loose weight',
  howItWork: 'Low carb diets restrict your carb intake in favor of protein and fat.',
  benefits: 'Research suggests that low carb diets may reduce risk factors for heart disease, including high cholesterol and blood pressure levels. They may also improve blood sugar and insulin levels in people with type 2 diabetes',
  downsides: `While the digital version of the program includes meal plans, recipes, a food tracker, virtual group sessions, at-home workouts, and more, it will cost you monthly to buy into the program`,
  summary: 'Low carb diets restrict your carb intake, which encourages your body to use more fat as fuel.They can help you lose weight and offer many other benefits.',
}, {
  id: 6,
  name: 'Intermittent fasting',
  type: 'To loose weight',
  howItWork: 'Low carb diets restrict your carb intake in favor of protein and fat.',
  benefits: 'Research suggests that low carb diets may reduce risk factors for heart disease, including high cholesterol and blood pressure levels. They may also improve blood sugar and insulin levels in people with type 2 diabetes',
  downsides: `While the digital version of the program includes meal plans, recipes, a food tracker, virtual group sessions, at-home workouts, and more, it will cost you monthly to buy into the program`,
  summary: 'Low carb diets restrict your carb intake, which encourages your body to use more fat as fuel.They can help you lose weight and offer many other benefits.',
}, {
  id: 7,
  name: 'The Volumetrics diet',
  type: 'To loose weight',
  howItWork: 'Low carb diets restrict your carb intake in favor of protein and fat.',
  benefits: 'Research suggests that low carb diets may reduce risk factors for heart disease, including high cholesterol and blood pressure levels. They may also improve blood sugar and insulin levels in people with type 2 diabetes',
  downsides: `While the digital version of the program includes meal plans, recipes, a food tracker, virtual group sessions, at-home workouts, and more, it will cost you monthly to buy into the program`,
  summary: 'Low carb diets restrict your carb intake, which encourages your body to use more fat as fuel.They can help you lose weight and offer many other benefits.',
}, {
  id: 8,
  name: 'The Mayo Clinic Diet',
  type: 'To loose weight',
  howItWork: 'Low carb diets restrict your carb intake in favor of protein and fat.',
  benefits: 'Research suggests that low carb diets may reduce risk factors for heart disease, including high cholesterol and blood pressure levels. They may also improve blood sugar and insulin levels in people with type 2 diabetes',
  downsides: `While the digital version of the program includes meal plans, recipes, a food tracker, virtual group sessions, at-home workouts, and more, it will cost you monthly to buy into the program`,
  summary: 'Low carb diets restrict your carb intake, which encourages your body to use more fat as fuel.They can help you lose weight and offer many other benefits.',
}, {
  id: 9,
  name: 'Low carb diets',
  type: 'To loose weight',
  howItWork: 'Low carb diets restrict your carb intake in favor of protein and fat.',
  benefits: 'Research suggests that low carb diets may reduce risk factors for heart disease, including high cholesterol and blood pressure levels. They may also improve blood sugar and insulin levels in people with type 2 diabetes',
  downsides: `While the digital version of the program includes meal plans, recipes, a food tracker, virtual group sessions, at-home workouts, and more, it will cost you monthly to buy into the program`,
  summary: 'Low carb diets restrict your carb intake, which encourages your body to use more fat as fuel.They can help you lose weight and offer many other benefits.',
}]